### ISSUE TITLE
Aspnet Monster Contest Solution

### ISSUE THREAD

**Issue by abdullah2993** [AspNetMonsters/IrrelevantCode#2]
The journey starts from the GitHub organization of [AspNetMonsters](https://github.com/AspNetMonsters). Once there if you scroll down you will see a weird looking [repository](https://github.com/AspNetMonsters/IrrelevantCode) which actually stands out due to its weird description which is :

> Not used, likely will remove

So if you open the code in that [repository](https://github.com/AspNetMonsters/IrrelevantCode) 
you will see [this](https://github.com/AspNetMonsters/IrrelevantCode/blob/master/src/IrrelevantCode/Program.cs):
![code](http://i.imgur.com/yxWBR1k.png)
looking at the code the `==` at the end of the `string interpolation format` in `Console.WriteLine` will assure you that its a `Base64` encoded string so time to decode it. I used an online [decoder](http://swisspouch.apphb.com/)
![decode](http://i.imgur.com/1hfUtUD.png)
press decode
![decoded](http://i.imgur.com/SHMyp7O.png)
or you can clone the [repository](https://github.com/AspNetMonsters/IrrelevantCode)  a do something like `System.Text.Encoding.UTF8.GetString(Convert.FromBase64String($"{whysosnoopy}{mid}{term}"))`
Now if you visit the [website](http://thisisnotacontest.azurewebsites.net/)
you will see this
![site](http://i.imgur.com/GDpordf.png)
but like anyone curious you will open the [source code](view-source:http://thisisnotacontest.azurewebsites.net/)
![source](http://i.imgur.com/hZIzbZl.png)
and will see some weird looking code in it

```
<form method="post">
    <div id="honey-pot" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Not a contest.</h4>
                </div>
                <div class="modal-body">
                    <p>If this were a contest, you'd put in a code here:</p>
                    <p><input name="secretCode" type="text" class="form-control" /></p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-remove"></i> Don't Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>
```

now if you scroll down further you will see the script files
`<script src="/js/site.min.js?v=-qyse9cmprVHnWt0HGWj0Paxf0JuLs9hEpIH7S0EMus"></script>`
now if you open the script file you will see
`function invokeTheNotContest(){$("#honey-pot").modal()}console.log("Oh, there's a contest.");`
now trigger the `invokeTheNotContest()` function from developer console you will see this dialogue
![modal](http://i.imgur.com/LEWxW1e.png) 
if you remember the `form` tag in the source code there was an input tag in it `<input name="secretCode" type="text" class="form-control" />` and the name of the parameter is `secretCode` if you remember correctly the was also a weird [line](https://github.com/AspNetMonsters/IrrelevantCode/blob/master/src/IrrelevantCode/Program.cs#L14) in the code so that has to be the `secretCode` you are looking for. 
Now just run the app and look at the value of `notusedanywhere` variable
![output](http://i.imgur.com/NnTR8xQ.png)
enter it into to the dialogue and hit `Don't Submit` and voila you are done
It will prompt you that you have won the contest and have you tweet @aspnetmonsters to let them know.

Note: for decoding base64 in core clr add `System.Text.Encoding` package to `dnxcore50:dependencies` and use the overload method
![img](http://i.imgur.com/4iM7Zpr.png)

**Comment by stimms** [comment]
Well I'm impressed.
